Загрузите данные в датафрейм.

```{r}
gmp <- read.table("https://raw.githubusercontent.com/SergeyMirvoda/da2016/master/classwork4/gmp.dat")
```

```{r}
gmp$pop <- gmp$gmp/gmp$pcgmp
```

```{r}
plot(pcgmp~pop, data=gmp, xlab="Население", log="xy",ylab="Доход на душу населения ($/человеко-год)", main="Метрополии США")

```


```{r}
estimate.scaling.exponent <- function(a, y0=6611, response=gmp$pcgmp,
                                        predictor = gmp$pop, maximum.iterations=100, deriv.step = 1/100,
                                        step.scale = 1e-12, stopping.deriv = 1/100) {
  mse <- function(a) { mean((response - y0*predictor^a)^2) }
  for (iteration in 1:maximum.iterations) {
    deriv <- (mse(a+deriv.step) - mse(a))/deriv.step
    a <- a - step.scale*deriv
    if (abs(deriv) <= stopping.deriv) { break() }
  }
  fit <- list(a=a,iterations=iteration,
              converged=(iteration < maximum.iterations))
  return(fit)
}
```

```{r}
estimate.scaling.exponent(0.15)
```

```{r}
curve(estimate.scaling.exponent, from=1, to=50, xlab="x", ylab="y")
```

